# Generated by Django 5.2.3 on 2025-07-11 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 11, 12, 22, 26, 621481, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
